# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Airport.create(name: 'Albuqerque', code: 'ABQ')
Airport.create(name: 'Albany', code: 'ALB')
Airport.create(name: 'Anchrage', code: 'ANC')
Airport.create(name: 'Asheville', code: 'AVL')
Airport.create(name: 'Aspen', code: 'ASE')
Airport.create(name: 'Atlanta', code: 'ATL')
Airport.create(name: 'Austin', code: 'AUS')
Airport.create(name: 'Baltimore', code: 'BWI')
Airport.create(name: 'Baton Rouge', code: 'BTR')
Airport.create(name: 'Billings', code: 'BIL')
Airport.create(name: 'Birmingham', code: 'BMH')
Airport.create(name: 'Bismarc', code: 'BIS')
Airport.create(name: 'Boise', code: 'BOI')
Airport.create(name: 'Boston', code: 'BOS')
Airport.create(name: 'Bozeman', code: 'BZN')
Airport.create(name: 'Casper', code: 'CPR')
Airport.create(name: 'Cedar Rapids', code: 'CID')
Airport.create(name: 'Charlston', code: 'CHS')
Airport.create(name: 'Charlotte', code: 'CLT')
Airport.create(name: 'Cheyenne', code: 'CYS')
Airport.create(name: "Chicago O'hare", code: 'ORD')
Airport.create(name: 'Chicago Midway', code: 'MDW')
Airport.create(name: 'Cincinnati', code: 'CVG')
Airport.create(name: 'Colorado Springs', code: 'COS')
Airport.create(name: 'Columbus', code: 'CMH')
Airport.create(name: 'Dallas Ft Worth', code: 'DFW')
Airport.create(name: 'Daytona Beach', code: 'DAB')
Airport.create(name: 'Denver Int', code: 'DEN')
Airport.create(name: 'Des Moines', code: 'DSM')
Airport.create(name: 'Detroit', code: 'DTW')
Airport.create(name: 'Durham/Raleigh', code: 'RDU')
Airport.create(name: 'El Paso', code: 'ELP')
Airport.create(name: 'Eugene', code: 'EUG')
Airport.create(name: 'Fairbanks', code: 'FAI')
Airport.create(name: 'Fargo', code: 'FAR')
Airport.create(name: 'Flagstaff', code: 'FLG')
Airport.create(name: 'Fresno', code: 'FAT')
Airport.create(name: 'Grand Forks', code: 'GFK')
Airport.create(name: 'Greensboro', code: 'GSO')
Airport.create(name: 'Hartford', code: 'BDL')
Airport.create(name: 'Helena', code: 'HLN')
Airport.create(name: 'Honolulu', code: 'HNL')
Airport.create(name: 'Houston int', code: 'HOU')
Airport.create(name: 'Indianapolis', code: 'IND')
Airport.create(name: 'Jackson', code: 'JAN')
Airport.create(name: 'Jacksonville', code: 'JAX')
Airport.create(name: 'Kansas City', code: 'MCI')
Airport.create(name: 'Knoxville', code: 'TYS')
Airport.create(name: 'Lafayette', code: 'LFT')
Airport.create(name: 'Las Vegas', code: 'LAS')
Airport.create(name: 'Lincoln', code: 'LNK')
Airport.create(name: 'Little Rock', code: 'LIT')
Airport.create(name: 'Long Beach', code: 'LGB')
Airport.create(name: 'Los Angeles', code: 'LAX')
Airport.create(name: 'Louisville', code: 'SDF')
Airport.create(name: 'Madison', code: 'MSN')
Airport.create(name: 'Memphis', code: 'MEM')
Airport.create(name: 'Miami Int', code: 'MIA')
Airport.create(name: 'Milwaukee', code: 'MKE')
Airport.create(name: 'Minneapolis', code: 'MSP')
Airport.create(name: 'Montgomery', code: 'MGM')
Airport.create(name: 'Nashville', code: 'BNA')
Airport.create(name: 'New Haven', code: 'HVN')
Airport.create(name: 'New Orleans', code: 'MSY')
Airport.create(name: 'New York JKF', code: 'JFK')
Airport.create(name: 'New York LaGuardia', code: 'LGA')
Airport.create(name: 'Newark', code: 'EWR')
Airport.create(name: 'Norfolk', code: 'ORF')
Airport.create(name: 'Oakland', code: 'OAK')
Airport.create(name: 'Oklahoma City', code: 'OKC')
Airport.create(name: 'Omaha', code: 'OMA')
Airport.create(name: 'Orange County', code: 'SNA')
Airport.create(name: 'Orlando Int', code: 'MCO')
Airport.create(name: 'Pensacola', code: 'PNS')
Airport.create(name: 'Philadelphia', code: 'PHL')
Airport.create(name: 'Phoenix', code: 'PHX')
Airport.create(name: 'Pittsburgh', code: 'PIT')
Airport.create(name: 'Portland, ME', code: 'PWM')
Airport.create(name: 'Portland, OR', code: 'PDX')
Airport.create(name: 'Providence', code: 'PVD')
Airport.create(name: 'Rapid city', code: 'RAP')
Airport.create(name: 'Reno', code: 'RNO')
Airport.create(name: 'Sacramento', code: 'SMF')
Airport.create(name: 'St Louis', code: 'STL')
Airport.create(name: 'Salt Lake City', code: 'SLC')
Airport.create(name: 'San Antonio', code: 'SAT')
Airport.create(name: 'San Diego', code: 'SAN')
Airport.create(name: 'San Francisco', code: 'SFO')
Airport.create(name: 'San Jose', code: 'SJC')
Airport.create(name: 'Seattle Int', code: 'SEA')
Airport.create(name: 'Spokane', code: 'GEG')
Airport.create(name: 'Tampa', code: 'TPA')
Airport.create(name: 'Topeka', code: 'FOE')
Airport.create(name: 'Toledo', code: 'TOL')
Airport.create(name: 'Tucson', code: 'TUS')
Airport.create(name: 'Washington DC Dulles', code: 'IAD')
Airport.create(name: 'Wichita', code: 'ICT')
Airport.create(name: 'Yellowstone', code: 'COD')

Flight.create(departure_id: 21, arrival_id: 37, start: (Time.now + 2.days), duration: 2.hours, empty_seats: 13)
Flight.create(departure_id: 20, arrival_id: 65, start: (Time.now + 3.hours), duration: 3.hours, empty_seats: 21)
Flight.create(departure_id: 20, arrival_id: 87, start: (Time.now + 8.hours), duration: 5.hours, empty_seats: 1)
Flight.create(departure_id: 20, arrival_id: 25, start: (Time.now + 6.hours + 30.minutes), duration: (3.hours + 30.minutes), empty_seats: 3)